# Path Configuration
audio_path: '/home/soonbeom/Projects/Dataset/saebyul_dataset/wav/star_kr_0u.wav'
model_path: './save/default/epoch1.pt'
wavernn_path: './save/wavernn/ljspeech_800k.pt'

# Feature Configuration
speaker: 0
num_speaker: 2
num_char: 47
min_note: 45
num_note: 36

length_c: 5 # consonant length
length_offset: 8 # 0.1s
min_unvoice: 20 # 0.3s
max_unvoice: 56 # 0.8s 
min_length: 80 # 1s
max_length: 400 # 5s

sample_rate: 22050
fft_size: 2048
hop_size: 275
win_size: 1100
mel_size: 80
mel_fmin: 40.0
mel_fmax: null
min_level_db: -100
ref_level_db: 20

# Model Configuration
text_embed_size: 256
prenet_size: [256, 128]
encoder_size: 128
encoder_K: 16

speaker_embed_size: 8
alignment_size: 256

decoder_size: 512
postnet_size: 256
postnet_K: 8

num_highways: 4
reduction: 1
dropout: 0.5
clip_grad_norm: 1.0

# WaveRNN Configuration
bits: 9
mu_law: true
pad: 2

mode: 'MOL'
upsample_factors: [5, 5, 11]
rnn_size: 512
fc_size: 512
compute_size: 128
res_out_size: 128
res_blocks: 10

batched_infer: true
target_size: 11000
overlap_size: 550 

# Inference Configuration
batch_size: 1
device: [0]